services:
  # Backend Service
  - type: web
    name: student-forum-backend
    runtime: python
    repo: https://github.com/samarshri/Temp
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app

    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.10.0

  # Frontend Service
  - type: web
    name: student-forum-frontend
    runtime: static
    repo: https://github.com/samarshri/Temp
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./build

    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: student-forum-backend
          property: host
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
